version: '16.10'

services:
  myDB:
    image: postgres:15.3
    container_name: CRM-LOA-DB
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=LOA-DB
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pdAdmin:
    image: dpage/pgadmin4
    container_name: LOA-pgadmin4
    restart: always
    depends_on:
      - myDB
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=juanignaciobisello@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json:a